// including cookies, headers or searchParams causes next.js to dynamically render

import { cookies } from "next/headers";

export const metadata = {
  title: "About Coderevolution",
  description: "Generated by me",
};

export default function About() {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  console.log(theme);
  // Won't be seen in the console, but in the terminal where project is running (server side)
  console.log("About Server Component");
  return <h1>About Me {new Date().toLocaleTimeString()}</h1>;
}
