import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    // default for children (if not specified within them)
    default: "Next.js Project",
    // will get inserted after child metadata title
    template: "%s | CodeRevolution",
  },
  description: "Generated by Next.js",
};
const headerStyle: React.CSSProperties = {
  padding: "20px",
  margin: "10px",
  backgroundColor: "#f8f9fa",
  textAlign: "center",
  borderBottom: "1px solid #dee2e6",
};

const footerStyle: React.CSSProperties = {
  padding: "20px",
  margin: "10px",
  backgroundColor: "#f8f9fa",
  textAlign: "center",
  borderTop: "1px solid #dee2e6",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={headerStyle}>
          <p>HEADER</p>
        </header>
        {children}
        <footer style={footerStyle}>
          <p>FOOTER</p>
        </footer>
      </body>
    </html>
  );
}
